openapi: 3.0.0
paths:
  /api/v1/math:
    get:
      operationId: MathController_execute
      parameters: []
      responses:
        '200':
          description: ''
  /api/v1/timer-control:
    post:
      operationId: DevicesController_updateTimerByDeviceCode
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimerControlRequest'
      responses:
        '201':
          description: ''
info:
  title: Home Automation API
  description: Home Automation API for IoT devices
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
      name: JWT
      description: Enter JWT auth token
      in: header
  schemas:
    StatusReportMessage:
      type: object
      properties: {}
    TimerStatus:
      type: string
      enum:
        - 'ON'
        - 'OFF'
    TimerControlRequest:
      type: object
      properties:
        code:
          type: string
          description: Device code. Must be unique
          examples:
            - D0001
            - D0002
            - D0003
          example: D0001
        status:
          description: Device state
          example: 'ON'
          $ref: '#/components/schemas/TimerStatus'
        minutes:
          type: number
          description: Timer countdown in minutes. Only minutes [0-59] are supported.
          example: 10
          default: 15
        seconds:
          type: number
          description: Timer countdown in seconds. Only seconds [0-59] are supported
          example: 30
          default: 0
      required:
        - code
        - status
