version: "3.8"

services:
  device-manager:
    build:
      context: ./manager
      dockerfile: Dockerfile
      args:
        - PORT=8000
        - BUILD_ENV=production
    container_name: iot-device-manager
    environment:
      NODE_ENV: production
      PORT: 8000
      ORIGIN: http://localhost:3000
      MQTT_HOST: mqtt-server
      DB_USER: device_manager
      DB_PASS: device_manager
      DB_NAME: device_manager
      DB_HOST: mysql-database
      DB_PORT: 3306
    depends_on:
      - mqtt-server
#      - mysql-database
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - IoT
#  mysql-database:
#    image: mysql:8.2
#    container_name: mysql-database
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: device_manager
#      MYSQL_USER: device_manager
#      MYSQL_PASSWORD: device_manager
#    restart: unless-stopped
#    networks:
#      - IoT
  mqtt-server:
    image: eclipse-mosquitto:2.0
    container_name: iot-mqtt-server
    volumes:
      - ./config/:/mosquitto/config/
    ports:
      - "1883:1883" # Default MQTT port
      - "9001:9001" # Default MQTT port for websockets
    restart: unless-stopped
    networks:
      - IoT
networks:
  IoT:
    driver: bridge
