openapi: 3.0.0
info:
  title: Simple Server API
  description: API for serving static files and managing a timer.
  version: 1.0.0
tags:
  - name: Power
    description: Device power management (ON/OFF)
  - name: Device
    description: Device information
  - name: Scheduler
    description: Device scheduler
servers:
  - url: http://localhost
    description: Local development server
  - url: http://192.168.1.2
    description: My home network
paths:
  /api/on:
    post:
      tags:
        - Power
      description: >-
        Starts the device timer for a specified duration.
        After the timer expires, the device will be turned off automatically.
      summary: Start the timer
      parameters:
        - name: min
          in: query
          schema:
            type: integer
          required: true
          description: Minutes to set the timer
        - name: sec
          in: query
          schema:
            type: integer
          required: true
          description: Seconds to set the timer
      responses:
        '200':
          description: Timer started successfully
          headers:
            Content-type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  active:
                    type: boolean
                    example: true
                  time:
                    type: integer
                    example: 60
        '400':
          description: Invalid query parameters or duration less than 10 seconds
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid query parameters or duration less than 10 seconds"
  /api/off:
    post:
      tags:
        - Power
      summary: Stop the timer
      description: Stops the device timer and turns off the device.
      responses:
        '200':
          description: Timer stopped successfully
          headers:
            Content-type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  active:
                    type: boolean
                    example: false
  /api/status:
    get:
      tags:
        - Device
      summary: Get the current status of the timer
      description: >-
        Returns the current status of the device timer.
        Whether the timer is active or inactive and the remaining time.
      responses:
        '200':
          description: Timer status retrieved successfully
          headers:
            Content-type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  active:
                    type: boolean
                    example: true
                  time:
                    type: integer
                    example: 30
  /api/config-update:
    get:
      tags:
        - Device
      summary: Update device configuration
      description: >-
        Updates the device configuration with new settings.
        The configuration includes the device name, version, and description.
      parameters:
        - name: name
          in: query
          schema:
            type: string
          required: false
          description: New device name
        - name: description
          in: query
          schema:
            type: string
          required: false
          description: >-
            New device description, it has to be short.
            max 64 characters.
        - name: startTime
          in: query
          schema:
            type: number
          required: false
          description: >-
            New device start time.
            It is important for the physical button.
            On the button click how long it has to start.
        - name: managerUrl
          in: query
          schema:
            type: string
          required: false
          description: >-
            New device manager URL.
            It is important for the device to communicate with the manager.
            It will work without it however for full potential it needs to be set properly.
      responses:
        '204':
          description: Configuration updated successfully
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid query parameters"
  /api/info:
    get:
      tags:
        - Device
      summary: Get server information
      description: >-
        Returns information about the server and disk usage.
        Disk usage is calculated as a percentage of used space to total space.
        File logs are stored on the device, and disk usage is important.
      responses:
        '200':
          description: Server information retrieved successfully
          headers:
            Content-type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: "D0001"
                    description: Device unique identifier
                  version:
                    type: string
                    example: "1"
                    description: Device version
                  current:
                    description: Active configuration of the device
                    type: object
                    properties:
                      name:
                        type: string
                        example: "MyServer"
                      description:
                        type: string
                        example: "A simple server"
                      startTime:
                        type: number
                        example: 10
                        description: Current start time for the physical button
                      managerUrl:
                        type: string
                        example: "http://192.168.1.2"
                        description: Current manager URL
                  defaults:
                    description: Default configuration of the device
                    type: object
                    properties:
                      name:
                        type: string
                        example: "DefaultServer"
                      description:
                        type: string
                        example: "Default server description"
                      startTime:
                        type: number
                        example: 10
                        description: Default start time for the physical button
                      managerUrl:
                        type: string
                        example: "http://192.168.1.3"
                        description: Default manager URL
                  disk:
                    description: Disk usage of the device
                    type: object
                    properties:
                      used:
                        type: integer
                        example: 1024
                      total:
                        type: integer
                        example: 2048
                      occupied:
                        type: string
                        example: "50.00%"
                  time:
                    description: System time
                    type: object
                    properties:
                      now:
                        type: integer
                        example: 1740858186087
                      str:
                        type: string
                        example: "Sat Mar 01 2025 23:43:06 GMT+0400"
                      iso:
                        type: string
                        example: "2025-03-01T19:43:06.087Z"
  /api/schedules:
    get:
      summary: Get list of schedules
      tags:
        - Scheduler
      responses:
        '200':
          description: List of schedules
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                      description: Unique identifier of the schedule. Array index.
                    name:
                      type: string
                      example: "Schedule 1"
                    active:
                      type: boolean
                      example: true
                      description: Whether the schedule is active or not
                    hour:
                      type: integer
                      example: 13
                      description: Hour value of the schedule. 24-hour format. 0-23.
                    minute:
                      type: integer
                      example: 30
                      description: Minute value of the schedule. 0-59.
                    weekdays:
                      type: string
                      example: "1,2,3,4,5"
                      description: Comma-separated list of weekdays. 0-6. 1 is Monday.
                    activateForSeconds:
                      type: integer
                      example: 360
                      description: Duration in seconds for how long it should be active. Min 60 seconds, max 3600 seconds.
    post:
      tags:
        - Scheduler
      summary: Scheduler action
      parameters:
        - name: action
          in: query
          schema:
            enum: [ 'ON', 'OFF' ]
          required: true
          description: Action to perform
      responses:
        '200':
          description: Schedule updated successfully
    put:
      tags:
        - Scheduler
      summary: Update scheduler parameters
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          required: true
          description: Schedule ID to update
        - name: hour
          in: query
          schema:
            type: integer
          required: true
          description: Hour value of the schedule. 24-hour format. 0-23.
        - name: minute
          in: query
          schema:
            type: integer
          required: true
          description: Minute value of the schedule. 0-59.
        - name: weekdays
          in: query
          schema:
            type: string
          required: true
          description: Comma-separated list of weekdays. 0-6. 1 is Monday and 0 is Sunday.
        - name: active
          in: query
          schema:
            type: boolean
          required: true
          description: Whether the schedule is active or not
        - name: activateForSeconds
          in: query
          schema:
            type: integer
          required: true
          description: Duration in seconds for how long it should be active. Min 60 seconds, max 3600 seconds.
      responses:
        '204':
          description: Schedule updated successfully
